{% set version = "0.6.0" %}

package:
  name: htmllistparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/htmllistparse/htmllistparse-{{ version }}.tar.gz
  sha256: 9ac274a165a02bf503656df4b48e1ae9eec0df40723a5f998f9023d3df3c8e32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - rehttpfs = htmllistparse.rehttpfs:main

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - beautifulsoup4
    - html5lib
    - requests
    - fusepy

test:
  imports:
    - htmllistparse

about:
  home: https://github.com/gumblex/htmllisting-parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python parser for Apache/nginx-style HTML directory listing
  dev_url: https://github.com/gumblex/htmllisting-parser

extra:
  recipe-maintainers:
    - holtgrewe
