{% set version = "0.5.2" %}

package:
  name: htmllistparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/htmllistparse/htmllistparse-{{ version }}.tar.gz
  sha256: ed864e1778257bbbc1ed0a865855ab846da4bf2b54733df2244978ae76cb474b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - rehttpfs = htmllistparse.rehttpfs:main

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - beautifulsoup4
    - html5lib
    - requests
    - fusepy

test:
  imports:
    - htmllistparse

about:
  home: https://github.com/gumblex/htmllisting-parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python parser for Apache/nginx-style HTML directory listing'
  dev_url: https://github.com/gumblex/htmllisting-parser

extra:
  recipe-maintainers:
    - holtgrewe
