travis:
  secure:
    BINSTAR_TOKEN: GBPJalwGqfV0Tf1R4jZVwkssJXLR+ltcCVZAbBIAO0U3r3bxldQyvM8t2Qd/D0bEyW+ldCO3j/h9rOomuZGh8f0VUwguq3aX3TBpNLkhR/qvzImRxBchwzeja83aBkpoGamsTGD4SxB71XhTyuaa7RRNfbSrgntVId1UjT60vkEGWz5NPSD/L9tJ4++bsHVOsbXK4GtILWn1zJ/6ZKmLYXGu7ghoLN7UhvsqmeeYW6NoxvH0aCAjHpWW/LMTpaZ5QGbTAixwtzWDU2XImGRTN1s6Jg6mEh0QLbWh1xLheVWcLDlv+/5dmmHgtd9+1ri2En3H6qyeTfZzC/2Ku4JmpVF4LFmIpAIrtuy2Q+n3SacDSmNEO0dpHHGyP621p0l4x5JvebiZxUzxQlKf8Hx6Wmc8PY4Ldz3E7wh8Dxfz0Yk3hKEZ8h0v01aGaNnYHx5v6ltFn+IBJPcFQozghMP29e1DK6qJ/qMqOGOXWlp8pd8PQm+Yn1ul9D2Wk35VNTyuHr+LXpNY7rkd7JrZwxxWFHPHDcqN8D4wXMonzEN/4M4ad6v+e5UhBP00sg87RnJ0DfpqhfGFjVLwnFCAwBFIZOvy1af8BiJtO64rLgjh0aYJaswRDDUuFfsEDlz2X+3aMgaoI6D/a1uKTxc28xnqfZhwidLopQUPx9ep5BwazKM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
